"""EmbedForge Prompts — stage-specific system prompts for the workflow pipeline."""

from prompts.stages import (
    CLARIFIER_SYSTEM_PROMPT,
    REFINER_SYSTEM_PROMPT,
    HARDWARE_SYSTEM_PROMPT,
    SOFTWARE_ARCH_SYSTEM_PROMPT,
    SOFTWARE_DETAILED_SYSTEM_PROMPT,
    CODEGEN_SYSTEM_PROMPT,
    REVIEWER_SYSTEM_PROMPT,
)

__all__ = [
    "CLARIFIER_SYSTEM_PROMPT",
    "REFINER_SYSTEM_PROMPT",
    "HARDWARE_SYSTEM_PROMPT",
    "SOFTWARE_ARCH_SYSTEM_PROMPT",
    "SOFTWARE_DETAILED_SYSTEM_PROMPT",
    "CODEGEN_SYSTEM_PROMPT",
    "REVIEWER_SYSTEM_PROMPT",
]
