"""AURIX Project Exporter — ADS-compatible project with iLLD integration."""

from __future__ import annotations

from typing import Any, Dict

from plugins.base import BoardConfig, ProjectExporter


class AurixProjectExporter(ProjectExporter):

    def get_build_system(self) -> str:
        return "aurix_ads"

    def export(self, production_files, test_files, mock_files, board_config, output_dir):
        result = {}
        for name, content in production_files.items():
            result[f"src/{name}"] = content
        for name, content in test_files.items():
            result[f"tests/{name}"] = content
        for name, content in mock_files.items():
            result[f"tests/mocks/{name}"] = content
        result.update(self.get_project_files(board_config))
        return result

    def get_project_files(self, board_config: BoardConfig) -> Dict[str, str]:
        mcu = board_config.mcu
        files = {}

        files["Makefile"] = f"""# AURIX {mcu} Project — generated by EmbedForge
TOOLCHAIN_PREFIX = tricore-elf-
CC = $(TOOLCHAIN_PREFIX)gcc
LD = $(TOOLCHAIN_PREFIX)gcc
OBJCOPY = $(TOOLCHAIN_PREFIX)objcopy
SIZE = $(TOOLCHAIN_PREFIX)size

MCU_FLAGS = -mcpu=tc39xx -msmall-const=8 -msmall-data=8

CFLAGS = $(MCU_FLAGS) -Wall -O2 -fdata-sections -ffunction-sections
LDFLAGS = $(MCU_FLAGS) -Wl,--gc-sections -T linker_script.ld -nostartfiles

# SDK paths (set AURIX_SDK_PATH env var)
INCLUDES = -Isrc/ -Isrc/Core/Inc
ifdef AURIX_SDK_PATH
INCLUDES += -I$(AURIX_SDK_PATH)/Libraries/iLLD/TC4DA/Tricore
INCLUDES += -I$(AURIX_SDK_PATH)/Libraries/Infra/Platform
endif

SOURCES = $(wildcard src/*.c) $(wildcard src/Core/Src/*.c)
OBJECTS = $(SOURCES:.c=.o)

TARGET = {board_config.name.replace("-", "_")}

all: $(TARGET).elf

$(TARGET).elf: $(OBJECTS)
\t$(LD) $(LDFLAGS) -o $@ $^
\t$(SIZE) $@

%.o: %.c
\t$(CC) $(CFLAGS) $(INCLUDES) -c $< -o $@

clean:
\trm -f $(OBJECTS) $(TARGET).elf $(TARGET).hex

.PHONY: all clean
"""

        files["src/Ifx_Cfg.h"] = f"""/* AURIX {mcu} configuration */
#ifndef IFX_CFG_H
#define IFX_CFG_H

#define IFX_CFG_DEVICE {mcu}

#endif
"""
        return files
