"""ESP-IDF Project Exporter — CMake + component structure for idf.py build."""

from __future__ import annotations

from typing import Any, Dict

from plugins.base import BoardConfig, ProjectExporter


class ESPProjectExporter(ProjectExporter):

    def get_build_system(self) -> str:
        return "esp_idf_cmake"

    def export(self, production_files, test_files, mock_files, board_config, output_dir):
        result = {}
        for name, content in production_files.items():
            result[f"main/{name}"] = content
        for name, content in test_files.items():
            result[f"tests/{name}"] = content
        for name, content in mock_files.items():
            result[f"tests/mocks/{name}"] = content
        result.update(self.get_project_files(board_config))
        return result

    def get_project_files(self, board_config: BoardConfig) -> Dict[str, str]:
        target = board_config.mcu.lower().replace("-", "")
        files = {}

        files["CMakeLists.txt"] = f"""cmake_minimum_required(VERSION 3.16)

set(EXTRA_COMPONENT_DIRS "main")
include($ENV{{IDF_PATH}}/tools/cmake/project.cmake)
project({board_config.name.replace("-", "_")})
"""

        files["main/CMakeLists.txt"] = f"""idf_component_register(
    SRCS "main.c"
    INCLUDE_DIRS "."
)
"""

        files["sdkconfig.defaults"] = f"""# Generated by EmbedForge for {board_config.name}
CONFIG_IDF_TARGET="{target}"
CONFIG_FREERTOS_HZ=1000
"""
        return files
