"""NXP MCUXpresso architecture rules."""

from __future__ import annotations

from typing import Any, Dict, List

from plugins.base import ArchitectureRulePack


class NXPArchitectureRules(ArchitectureRulePack):
    def get_rules_text(self) -> str:
        return "\n".join([
            "NXP MCUXpresso SDK Architecture Rules:",
            "1. Call BOARD_InitPins() and BOARD_InitClocks() before peripheral init.",
            "2. Use CLOCK_* APIs for clock configuration — never write RCC registers directly.",
            "3. Peripheral drivers follow fsl_<periph>.h naming (e.g., fsl_usart.h).",
            "4. Config structs use <PERIPH>_GetDefaultConfig() + modify pattern.",
            "5. Interrupt handlers: <PERIPH>_IRQHandler calls driver handler or user callback.",
            "6. Pin mux configured via IOCON or IOMUXC — use pin_mux.c generated by MCUXpresso Config Tools.",
            "7. DMA uses EDMA or DMA engine; link handles before starting transfer.",
            "8. Check kStatus_Success return from driver APIs.",
        ])

    def get_init_pattern(self, driver: str) -> str:
        return ""

    def get_naming_conventions(self) -> Dict[str, Any]:
        return {
            "function_prefix": "fsl_<periph>",
            "config_struct": "<PERIPH>_config_t",
            "handle_type": "<periph>_handle_t",
            "status_type": "status_t (kStatus_Success, kStatus_Fail)",
        }

    def validate_code(self, code: str) -> List[str]:
        return []
