"""Microchip Harmony architecture rules."""
from __future__ import annotations
from typing import Any, Dict, List
from plugins.base import ArchitectureRulePack

class MicrochipArchitectureRules(ArchitectureRulePack):
    def get_rules_text(self) -> str:
        return "\n".join([
            "Microchip MPLAB Harmony v3 Architecture Rules:",
            "1. Use MHC/MCC-generated PLIB wrappers (e.g., SERCOM0_USART_Write).",
            "2. Peripheral init generated by MHC into plib_<periph>.c — do not modify.",
            "3. Pin config via Pin Manager in MHC — generates plib_port.c.",
            "4. SAM SERCOM is multiplexed (UART/SPI/I2C share same peripheral block).",
            "5. Callback registration: <PERIPH>_CallbackRegister(handler, context).",
            "6. Error handling: check return bool or status enum.",
            "7. DMA via DMAC PLIB — configure channel before starting transfer.",
            "8. System services (SYS_*) for higher-level abstractions.",
        ])
    def get_init_pattern(self, driver: str) -> str:
        return ""
    def get_naming_conventions(self) -> Dict[str, Any]:
        return {"function_prefix": "<PERIPH>N_<Function> (e.g., SERCOM0_USART_Write)",
                "callback": "<PERIPH>_CallbackRegister", "plib_prefix": "plib_"}
    def validate_code(self, code: str) -> List[str]:
        return []
